name: cricketenv
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.10.0
  - appnope=0.1.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - bandit=1.8.6
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpp-expected=1.1.0
  - cycler=0.12.1
  - debugpy=1.8.15
  - decorator=5.2.1
  - defusedxml=0.7.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - fmt=11.2.0
  - fonttools=4.59.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - gitdb=4.0.12
  - gitpython=3.1.43
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - lerc=4.0.0
  - libarchive=3.8.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.24
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libkrb5=1.21.3
  - liblapack=3.9.0
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libmamba=2.3.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsolv=0.7.35
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lmdb=0.9.29
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.3.1
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mistune=3.1.3
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - openjpeg=2.5.3
  - openssl=3.5.1
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.12.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.1
  - platformdirs=4.3.8
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyobjc-core=11.0
  - pyobjc-framework-cocoa=11.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.12.9
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rpds-py=0.26.0
  - send2trash=1.8.3
  - setuptools=78.1.1
  - simdjson=3.13.0
  - six=1.17.0
  - smmap=5.0.2
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlite=3.50.4
  - stack_data=0.6.3
  - stevedore=5.4.1
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250708
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - astunparse==1.6.3
      - click==8.2.1
      - dnspython==2.7.0
      - email-validator==2.2.0
      - fastapi==0.116.1
      - fastapi-cli==0.0.8
      - fastapi-cloud-cli==0.1.5
      - flatbuffers==25.2.10
      - gast==0.6.0
      - google-pasta==0.2.0
      - grpcio==1.74.0
      - h5py==3.14.0
      - httptools==0.6.4
      - keras==3.11.1
      - libclang==18.1.1
      - markdown==3.8.2
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - mypy==1.17.1
      - mypy-extensions==1.1.0
      - namex==0.1.0
      - numpy==2.1.3
      - opt-einsum==3.4.0
      - optree==0.17.0
      - pbr==6.1.1
      - protobuf==5.29.5
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - rich==14.1.0
      - rich-toolkit==0.14.9
      - rignore==0.6.4
      - ruff==0.12.7
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - sentry-sdk==2.34.1
      - shellingham==1.5.4
      - starlette==0.47.2
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - typer==0.16.0
      - typing-inspection==0.4.1
      - uvicorn==0.35.0
      - uvloop==0.21.0
      - watchfiles==1.1.0
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
